baseURL = 'https://kazflora.online/'
languageCode = 'ru'
title = 'Kazflora'
theme = 'hugo-index'

enableRobotsTXT = true

[sitemap]
 changeFreq= 'daily'
 filename= 'sitemap.xml'
 priority = '1'

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2


